name: Sum Tests

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'  

    - name: Installer dépendances
      run: |
        python -m pip install --upgrade pip
        pip install poja

